services:
  - type: worker
    name: visa-alert-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: API_ID
        fromSecret: API_ID
      - key: API_HASH
        fromSecret: API_HASH
      - key: PHONE_NUMBER
        fromSecret: PHONE_NUMBER
